### ISSUE TITLE
nanomq broker Segmentation fault.

### ISSUE THREAD

**Issue by lee-emqx** [nanomq/nanomq#273] opened 2021-12-30 07:58 UTC
When I use mqtt client subscribe topic #, and I cancel it by hit Ctrl-c, nanomq broker will output Segmentation fault directly.

**Comment by wanghaEMQ** [comment] 2021-12-30 10:29
Hi, I noticed this bug which was caused by system_topic. I fixed it at #274.

**Comment by wanghaEMQ** [comment] 2021-12-30 10:32
If there are no problems, I will close this issue later.

**Comment by JaylinYu** [comment] 2021-12-30 10:48
Temp fix for now.

**Closed** 2021-12-30 10:48 UTC
Labels: bug
