### ISSUE TITLE
nanomq 0.22 - MQTT client receives duplicate messages even if message does not match other topics in the subscription set

### ISSUE THREAD

**Issue by reubenmiller** [nanomq/nanomq#1817] opened 2024-06-28 09:45 UTC
**Describe the bug**

In nanomq 0.22, if an MQTT client subscribes to multiple topics, then if a message matches one of the given subscriptions, then the message is received multiple times, 1 per topic, regardless if the other topic subscriptions match the incoming message or not.

The bug seems to be introduced in 0.22, as nanomq 0.21 behaves as expected when subscribing to multiple topics in the same subscription.

Below shows an example of the the error scenario, where only 1 message is published to the `topic1`, but it is received multiple times by the MQTT client (in this case `mosquitto_sub`).

**0.22.0 - :x: Incorrect: Duplicate message delivered**

```sh
docker rm nanomq -f
docker run --name nanomq -d -p 1883:1883 emqx/nanomq:0.22
mosquitto_pub -r -t "topic1" -m "hello"
mosquitto_sub -t topic1 -t topic2 -t topic3 -v
```
*Output*
```sh
topic1 hello
topic1 hello
topic1 hello
```

**Expected behavior**

If a client subscribes to multiple topics in the `SUBSCRIBE`, the client should only receive messages which are matching the topics and not duplicated based on non-matching topics.

**Actual Behavior**

The client receives duplicated messages (1 per topic) regardless if the message matches the other topics included in the SUBSCRIBE group or not.

**To Reproduce**

The bug can be reproduced by using the public docker `emqx/nanomq:0.22` image and `mosquitto_sub`.

**0.22.0 - :x: Incorrect: Duplicate message delivered**

```sh
docker rm nanomq -f
docker run --name nanomq -d -p 1883:1883 emqx/nanomq:0.22
mosquitto_pub -r -t "topic1" -m "hello"
mosquitto_sub -t topic1 -t topic2 -t topic3 -v
```

The output shows the `hello` message being delivered multiple times, even though there is only 1 subscription to the matching topic, `topic1`.

```sh
topic1 hello
topic1 hello
topic1 hello
```

Adding a new unrelated subscription to the same client, shows that the received messages has increased to 4 (one per topic)

```sh
mosquitto_sub -t topic1 -t topic2 -t topic3 -t topic4 -v
```

The output shows the `hello` message being delivered multiple times, even though there is only 1 subscription to the matching topic, `topic1`.

*Output*

```sh
topic1 hello
topic1 hello
topic1 hello
topic1 hello
```

Reverting back to nanomq 0.21, then the subscriptions behave as expected, and only 1 message is received.

**0.21.0 - :white_check_mark: Correct: Only one message delivered**

```sh
docker rm nanomq -f
docker run --name nanomq -d -p 1883:1883 emqx/nanomq:0.21
mosquitto_pub -r -t "topic1" -m "hello"
mosquitto_sub -t topic1 -t topic2 -t topic3 -v
```
*Output*
```sh
topic1 hello
```

**Environment Details**
 - NanoMQ version: `0.22.0` via docker image `emqx/nanomq:0.22`
 - Operating system and version: `MacOS` - `Darwin hostname 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64`
 - Compiler and language used: `command line, mosquitto_sub`
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by reubenmiller** [comment] 2024-06-28 09:50
Interesting enough, the duplication of messages only occurs if the messages are published with the RETAINED flag.

**Comment by reubenmiller** [comment] 2024-06-28 11:11
Further debugging reveals that the likely root cause of this issue is due to the following NanoNNG Pull Request:

* https://github.com/nanomq/NanoNNG/pull/970

I was able to confirm this by compiling nanomq using NanoNNG before and after the PR was merged, and before the PR was merged, the retained messages were not being duplicated, and after the PR is merged, the messages ARE duplicated.

**Pass -  With nng @ bd809ae063c6778916d873c7c68dbbb93c5ca032**

Using `nanomq` with [nng@bd809ae063c6778916d873c7c68dbbb93c5ca032](https://github.com/nanomq/NanoNNG/commit/bd809ae063c6778916d873c7c68dbbb93c5ca032) the retained messages are not duplicated:

```sh
cd nng
git checkout bd809ae063c6778916d873c7c68dbbb93c5ca032
cd ..
mkdir -p build
cd build && cmake -DNNG_ENABLE_SQLITE=ON .. && make
```

**Fail - With nng @ 3460901a9554e9361af16703d708d2572f0b4d58**

Using `nanomq` with [nng@3460901a9554e9361af16703d708d2572f0b4d58](https://github.com/nanomq/NanoNNG/commit/3460901a9554e9361af16703d708d2572f0b4d58) introduces the buggy behaviour where the retained messages are duplicated:

```sh
cd nng
git checkout 3460901a9554e9361af16703d708d2572f0b4d58
cd ..
mkdir -p build
cd build && cmake -DNNG_ENABLE_SQLITE=ON .. && make
```

**Comment by JaylinYu** [comment] 2024-07-01 12:52
Bug identified, root cause is exactly as you said. Thanks for the detailed debugging information.
WIll fix it soon. Need to figure out a way to make retain msg valid in topic reflection.

**Comment by JaylinYu** [comment] 2024-07-02 11:34
fix merged

**Closed** 2024-07-03 11:11 UTC
Labels: bug
