### ISSUE TITLE
HTTP authentication requests with local IP addresses in URL makes Node.js respond with bad request

### ISSUE THREAD

**Issue by laszlotar** [nanomq/nanomq#1625] opened 2024-01-23 18:34 UTC
**Describe the bug**
Error occurs when using internal IP addresses in URLs for the HTTP authentication feature.
When using internal IP addresses, Node.js returns a 400 status without the request being processed, most probably because of an error in the request header. When using fully qualified domain names or outside IP addresses, the requests are processed without a problem.

**To Reproduce**
1) Clean install NanoMQ

2) Add to configuration:
http_auth = {
    auth_req {
            url = "http://10.1.0.1:8080/nanomq/auth/"
            method = "post"
            headers.content-type = "application/json"
            params = {username="%u",password="%P"}
    }
}

3) On the machine 10.1.0.1 initialize a Node.js app and edit index.js:
require('http').createServer({maxHeaderSize:64000},function(request,response,error){
	if (error) console.log("ERROR:",error);
	const bodyStream = [];
	response.on("error", (error) => {
			console.log("ERROR:", error);
			response.statusCode = 500;
			return response.end();
	});
	request.on("data",(chunk)=>{
			bodyStream.push(chunk);
	}).on('end',()=>{
			const bufferData = Buffer.concat(bodyStream);
			const requestBody =  JSON.parse(bufferData) || {};
			console.log("BODY:",requestBody);
	});
	response.statusCode=200;
	response.end();
}).listen(8080,"0.0.0.0",()=>{console.log("LOG: server started")});

4) Run Node app on 10.1.0.1

5) Tail the log of NanoMQ and look for this error:
ERROR /home/runner/work/nanomq/nanomq/nng/src/sp/protocol/mqtt/auth_http.c:314 send_request: HTTP Server Responded: 400 Bad Request

6) Notice also that request do not reach processing in Node.js

**Environment Details**
 - NanoMQ version: v0.20.8-4
 - Operating system and version: Debian 11
 - Web server: Node.js v12.22.12

**Additional context**
Problem occurs with Node.js only. PHP processes the requests without problem.
Problem persists also when using the same server and 127.0.0.1 in the auth_req URL.
After reading about oversize headers and Node.js, I added the maxHeaderSize:64000 option to rule out this as the source of the problem.

**Comment by wanghaEMQ** [comment] 2024-01-25 09:16
@laszlotar 
Try this.
```
http_auth = {
auth_req {
url = "http://10.1.0.1:8080/nanomq/auth"
method = post
headers.content-type = "application/json"
params = {username="%u",password="%P"}
}
}
```

**Comment by laszlotar** [comment] 2024-01-25 12:46
Tried removing the trailing slash from the URL and tried changing the method to post with and without quotes. Unfortunately it did not help, the 400 response still persists.

**Comment by wanghaEMQ** [comment] 2024-01-26 09:21
Sorry. I have no experience with nodejs. But it seems the problem is the nodejs code instead of nanomq or network.

**Comment by tglane** [comment] 2024-02-01 13:28
I had the same issue when using node as the webhook handler for http auth but I guess I found a solution for this. If you use `POST` as method instead of `post` the request gets handled by node and reaches the request handler.

**Comment by laszlotar** [comment] 2024-02-01 18:57
Indeed, the solution above did fix the problem with the request. Thank you so much @tglane !

**Comment by tglane** [comment] 2024-02-05 07:50
I created a [PR](https://github.com/nanomq/NanoNNG/pull/846) that was already merged in the NNG repository to always capitalize the method string in a http request.
When the submodule gets updated this issue should be fixed.

**Comment by laszlotar** [comment] 2024-02-06 12:28
Greatly appreciated. I am still wondering though, why this issue only affected requests with local addresses. (Maybe proxies and firewalls processing request are doing some rewriting in the background themselves. 🤔) Anyways, I will be closing this issue. Thank you Timo for your contribution!

**Closed** 2024-02-06 17:38 UTC
Labels: Investigation
